---
- name: Generating Access Switches configurations
  template: src=simple_switch.j2 dest=/home/amartinez/pynet/ANSIBLE/roles/ACCESS_SWITCH/configs/{{item.hostname}}.txt
  with_items: "{{acc_switch}}"
            
